### PR TITLE
FTFY.

### PR DESCRIPTION
**Pull request by hexameron**
You missed a bit.

### CODE REVIEW

**Comment by hexameron** [comment]
I see that Google have caught up with Mesa-11.0.4 , so it will be tricky to make sure the "modified" version gets built. The Mesa overlay will need continuous updating as Google update the version numbers.

**Comment by tohipfortheroom** [comment]
Mesa is building correctly in my current builds, I got it to stop failing by adding the raspberry pi 2 to the ebuild within the cros_sdk currently the the no-splash patch is failing me

**Comment by Hexxeh** [comment]
The no-splash patch fails the sandbox, because of the CROS_WORKON_OUT_OF_TREE_BUILD thing. Why is that patch necessary, by the way?

As for mesa versioning, you can mask newer versions that Google might update to, or depend on the specific version that you added from the BSP.

Any reason the Mesa changes can't be upstreamed to the respective projects?

**Comment by Hexxeh** [comment]
Also, have you given any thought to video decode acceleration? I've got a similar set of patches I was working on and the general performance is pretty good, but video decode lets it down as ffmpeg hammers the CPU. I'm working on OpenMAX integration to help this, but I'm curious if there's a better approach.

**Comment by ric96** [comment]
we can try to implement http://dri.freedesktop.org/wiki/VC4/ 
it kind of works on raspbian but its not 100% ready.

**Comment by Hexxeh** [comment]
That's exactly what this overlay does.

**Comment by tohipfortheroom** [comment]
https://drive.google.com/folderview?id=0ByKtv85qlyQDNm41TWlqUXg5azA&usp=sharing

These are the three packages that are currently failing

**Comment by tohipfortheroom** [comment]
the no-splash patch is a Utility that dumps a png image to the frame buffer, why do you believe its not needed any more ?

**Comment by ric96** [comment]
the patches for ply are not being implemented due to some read only permission error:

[vc4.patch.txt](https://github.com/tohipfortheroom/Chromium-OS-Overlays/files/56075/vc4.patch.txt)

**Pull request merged**
